import Head from 'next/head'
import { ReactElement } from 'react'

import GeneralLayout from '../../components/Layouts/GeneralLayout'
import NavButton from '../../components/UI/NavButton'

import { TNextPageWithLayout } from '../../types'

const Login: TNextPageWithLayout = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      LOGIN PAGE
      <br />
      <NavButton to={'/home'} />
    </div>
  )
}

Login.getLayout = (page: ReactElement) => {
  return (
    <GeneralLayout>
      {page}
    </GeneralLayout>
  )
}

export default Login
